# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e34e3cad35708fde34f617c1e562c234581794a6f5b80ed80feb72434ab6817e21cab4efa1e196fd81c4734f15399b7c4399dd8441fbc13218f3535f4a0827ce

test:
  secret_key_base: 80a383c20104f0da6c3d896a5835fa64f3c6993bea01deb8d5a11773e4a9113a4904d51f62a573d8ea1572886dcd29babfa3bc734fe52bf623b869a1e370127a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
